// docs/src/components/Header.svelte
<script lang="ts">
  import { metadata } from "$stores/metadata.store"
  import { pointer } from "$stores/pointer.store"
  import { screen } from "$stores/screen.store"
  import { theme } from "$stores/theme.store"

  import Logo from "./Logo.svelte"

  export let size = 12
</script>

<header
  class="h-screen flex items-center justify-center p-4"
  style:background={$theme.accent}
>
  <div>
    <h1><Logo {size} fill={$theme.light} /></h1>
    <p>{$metadata.description}</p>
    <p>screen: {$screen.width}px x {$screen.height}px</p>
    <p>pointer: {$pointer.x}px x {$pointer.y}px</p>
    <code>pnpm add onno</code>
    <label class="flex items-center space-x-2">
      <span>size:</span>
      <input type="range" bind:value={size} min={1} max={20} />
      <span>{size}</span>
    </label>
  </div>
</header>

// packages/onno-app/src/components/header.vue
<template>
  <header :style="{ background }">
    <v-logo v-bind="$props"/>
    <p>Responsive style props for building themed design systems.</p>
    <code>yarn add onno</code>
  </header>
</template>

<script>
import props from "~/common/props"
import VLogo from "./logo"

export default {
  props,
  components: {
    VLogo
  }
}
</script>

<style>
header {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  text-align: center;
}
header p {
  font-size: 1.5rem;
  max-width: 28ch;
  margin: 2em 0;
}
header code {
  background: rgba(255, 255, 255, 0.2);
  padding: 1em 2em;
}
</style>
